spring.datasource.url=jdbc:mysql://localhost:3306/foodhub
spring.datasource.username=root
spring.datasource.password=Pratik@29

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key.id=rzp_test_TKyhtuSCioLNk0
razorpay.key.secret=O3R6bAwMf9gkZcl4RJF4XrlK

server.port=8083
