spring.datasource.url=jdbc:mysql://localhost:3306/foodhub
spring.datasource.username=root
spring.datasource.password=Pratik@29

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083
